### ISSUE TITLE
Handle potentially null search fields

### ISSUE THREAD

**Issue by Bobakanoosh** [caneara/quest#11]
I'm wanting to search on two columns, one of which is nullable. At the moment I get `str_replace(): Argument #3 ($subject) must be of type array|string, null given` when doing so, so I suspect there isn't built-in support for this.

Is there a workaround for this?

**Comment by mattkingshott** [comment]
You could try casting the potentially nullable column to an empty string within the database query e.g. using `COALESCE` in MySQL.
