### ISSUE TITLE
Matching extra characters

### ISSUE THREAD

**Issue by iambateman** [caneara/quest#8]
First of all, great package...thanks!

I'm having an issue with extra characters and slight misspellings. I wasn't sure if this was expected behavior:

Matching for `guacamole`...if I type:
- `guac` it works
- `guacamolee` does not work
- `guacemole` does not work

Am I doing something wrong?

**Comment by mattkingshott** [comment]
Hey there.

Can you show me your actual query? Thanks!

**Comment by iambateman** [comment]
Sorry to bug you...I figured it out.

It looks like it *was* matching, but it was returning a _fuzzy_relevance_ much lower than I expected. Thanks!
