### ISSUE TITLE
_fuzzy_relevance_* is not limited to 100

### ISSUE THREAD

**Issue by grabelle** [caneara/quest#9]
Hello
First of all, thanks for all the job. From the documentation I understand that the relevance is between 0 and 100 ... but I have lus more than that

![image](https://user-images.githubusercontent.com/5048627/211899071-3927fb27-c59b-4a92-9392-6fbef949becd.png)

![image](https://user-images.githubusercontent.com/5048627/211899416-f530f1b5-ff58-4cd7-a525-91ed6128cf59.png)

do you have any idea ?
thanks a lot

**Comment by grabelle** [comment]
It seems taht the max is 295 ... and the _fuzzy_relevance_ is not divided by the number of column so it can be 590 if two field match exacly

**Comment by mattkingshott** [comment]
Thanks. I’ve updated the readme 👍🏻
